# -*- coding: utf-8 -*-
"""Tech Challange 02 - Time Series Fase 02

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CO-zkpknuRTVUVjqIUkDbVEfVJJj2WCf
"""

import pandas as pd

#Avisos
import warnings
warnings.filterwarnings('ignore')

"""# New Section"""

df=pd.read_csv("/content/Dados Históricos - Ibovespa(6 meses).csv", sep=",", parse_dates=["Data"])
df.head()

df.info()

df.head()

def convert_to_float(value):
    return float(value.replace("M", "").replace(",", "."))

df["Vol."] = df["Vol."].apply(convert_to_float)

print(df)

def convert_to_floats(value):
    return float(value.replace("%", "").replace(",", "."))

df["Var%"] = df["Var%"].apply(convert_to_floats)

print(df)

df.info()

